[workspace]
resolver = "2"
members = ["crates/cli", "crates/stealer"]
default-members = ["crates/stealer"]

# 定义工作区级别的公共包属性
[workspace.package]
version = "0.3.2-alpha2"    # 统一版本号
authors = ["Hammerklavier"]
edition = "2021"
